### ISSUE TITLE
Different results between espacenet and API 

### ISSUE THREAD

**Issue by eunbee31** [gsong/python-epo-ops-client#51]
Hello,

I would like to know if any of you has encountered the same issue as me.
Actually I get the feeling that the result is different from what we get via Espacenet platform and from the API.
I don't have the same number of documents and the same relevant documents.

Thanks,

**Comment by Polindem** [comment]
Hi!
It could be due to the fact that each patent has different doc numbers associated as far as the priority number, application number and publication number are different, so you should pay attention to them. The one you need to consult (the epodoc) is the publication number. 
<img width="697" alt="Screenshot 2021-08-28 at 19 45 55" src="https://user-images.githubusercontent.com/61337774/131226455-06093cb3-a806-41f7-ba17-67c31c8b35d7.png">
